# Generated by Django 3.2.7 on 2021-12-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='kind',
            field=models.CharField(blank=True, choices=[('hi', 'History'), ('rm', 'roman')], max_length=200, null=True),
        ),
    ]
