# Generated by Django 3.2.7 on 2021-12-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='kind',
            field=models.CharField(blank=True, choices=[('History', 'hi'), ('Roman', 'rm')], max_length=200, null=True),
        ),
    ]
