# Generated by Django 3.2.7 on 2021-12-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
