# Generated by Django 3.2.7 on 2021-12-20 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_pages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pages',
            new_name='year',
        ),
    ]
