# Generated by Django 3.2.7 on 2021-12-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
