# Generated by Django 3.2.7 on 2021-12-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_is_valid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_valid',
            new_name='available',
        ),
    ]
